### ISSUE TITLE
执行 "dva g route users"报错

### ISSUE THREAD

**Issue by Kilims** [sorrycc/blog#40]
OS: win64
nodeversion: v7.7.2
npm version: 5.0.3
dva-cli version: 0.7.8

错误为：

dva g route users
D:\node\node_modules\dva-cli\bin\dva-generate
      create  routeComponent src/routes/Users.js, src/routes/Users.cs
s
TypeError: root.findRouters(...).getRouterInfo is not a function
    at transform (D:\node\node_modules\dva-cli\node_modules\dva-ast\l
ib\transform.js:42:32)
    at exports.default (D:\node\node_modules\dva-cli\node_modules\dva
-ast\lib\api\index.js:46:36)
    at D:\node\node_modules\dva-cli\lib\generate.js:92:27
    at generate (D:\node\node_modules\dva-cli\lib\generate.js:108:11)
    at Object.<anonymous> (D:\node\node_modules\dva-cli\bin\dva-gener
ate:11:27)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by mmming0821** [comment]
same issue

**Comment by sorrycc** [comment]
请到 https://github.com/dvajs/dva/issues 这里提问。
