### ISSUE TITLE
按步骤，到第四步出错

### ISSUE THREAD

**Issue by yanhuangxiaoguang** [sorrycc/blog#42]
@sorrycc 执行到第四步报错，前面都能正确访问...api/users .
E:\iSearch6\user-dashboard>dva g route users
E:\nodejs\node_global\node_modules\dva-cli\bin\dva-generate
      create  routeComponent src/routes/Users.js, src/routes/Users.css
TypeError: root.findRouters(...).getRouterInfo is not a function
    at transform (E:\nodejs\node_global\node_modules\dva-cli\node_modules\dva-as
t\lib\transform.js:42:32)
    at exports.default (E:\nodejs\node_global\node_modules\dva-cli\node_modules\
dva-ast\lib\api\index.js:46:36)
    at E:\nodejs\node_global\node_modules\dva-cli\lib\generate.js:92:27
    at generate (E:\nodejs\node_global\node_modules\dva-cli\lib\generate.js:108:
11)
    at Object.<anonymous> (E:\nodejs\node_global\node_modules\dva-cli\bin\dva-ge
nerate:11:27)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by sorrycc** [comment]
请到 https://github.com/dvajs/dva/issues 这里提问。
