### ISSUE TITLE
Error: connect ECONNREFUSED 

### ISSUE THREAD

**Issue by QuietHeartThinkingFar** [sorrycc/blog#69]
按照antp的项目说明中的配置 https://pro.ant.design/docs/server-cn#从-mock-直接切换到服务端请求
export default (noProxy ? {
  'GET /api/(.*)': 'http://192.168.10.63:8080/api/',
} : delay(proxy, 1000));
报如下错误
Error: connect ECONNREFUSED 192.168.10.63:8080
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)

**Comment by xiaohuoni** [comment]
并不是这么配置的。这个是配置mock的。你要用代理。可以在webpackrc.js里面配置
